#https://taskfile.dev/
version: '3'

includes:
  ci: taskfile-ci.yml 

tasks:

  tools:
    desc: 'Install all tools used in this project'
    cmds:
      - task: ci:gofumpt
      - task: ci:lint-version

  test:
    desc: 'run Go tests'
    cmds:
      - go test ./...

  ci:
    desc: 'do all the checks'
    cmds:
      - task: ci:tidy
      - task: ci:format
      - task: ci:lint
      - task: test

  install:
    desc: 'build the project'
    cmds:
      - go build
      - go install

  run:
    desc: 'run the project'
    cmds:
      - go run . 

  sync:
    desc: 'download all external libraries'
    cmds:
      - mkdir -p ui/static
      - wget -O ui/static/mermaid.min.js https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
      - wget -O ui/static/highlight.min.js https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
