#https://taskfile.dev/
version: '3'

includes:
  ci: taskfile-ci.yml 

vars:
  BOXICONS_VERSION: 2.1.4
  HIGHLIGHT_JS_VERSION: 11.9.0

tasks:

  tools:
    desc: 'Install all tools used in this project'
    cmds:
      - task: ci:gofumpt
      - task: ci:lint-version

  test:
    desc: 'run Go tests'
    cmds:
      - go test ./...

  ci:
    desc: 'do all the checks'
    cmds:
      - task: ci:tidy
      - task: ci:format
      - task: ci:lint
      - task: test

  install:
    desc: 'build the project'
    cmds:
      - go build
      - go install

  run:
    desc: 'run the project'
    cmds:
      - go run . 

  external:
    desc: 'download all external libraries'
    cmds:
      - mkdir -p ui/static
      - wget -q -O ui/static/mermaid.min.js https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js      
      #- wget -q -O ui/static/mermaid.min.js https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      - wget -q -O ui/static/highlight.min.js https://cdnjs.cloudflare.com/ajax/libs/highlight.js/{{.HIGHLIGHT_JS_VERSION}}/highlight.min.js
      - wget -q -O ui/static/highlight.min.css https://cdnjs.cloudflare.com/ajax/libs/highlight.js/{{.HIGHLIGHT_JS_VERSION}}/styles/default.min.css
      - wget -q -O ui/static/boxicons.js https://unpkg.com/boxicons@{{.BOXICONS_VERSION}}/dist/boxicons.js
      - wget -q -O ui/static/boxicons.min.css https://unpkg.com/boxicons@{{.BOXICONS_VERSION}}/css/boxicons.min.css
      - mkdir -p ui/static/fonts
      - wget -q -O ui/static/fonts/boxicons.woff2 https://cdn.jsdelivr.net/npm/boxicons@latest/fonts/boxicons.woff2
      - wget -q -O ui/static/fonts/boxicons.woff https://cdn.jsdelivr.net/npm/boxicons@latest/fonts/boxicons.woff
      - wget -q -O ui/static/fonts/boxicons.ttf https://cdn.jsdelivr.net/npm/boxicons@latest/fonts/boxicons.ttf
